sinks:
  datadog:
    addr: 127.0.0.1
    port: 8125
    tags: [requestcount, requestlatency]
  newrelic:
    applicationName: api-name
    licenseKey: api-key
    ignoredStatusCodesStart: 400
    ignoredStatusCodesEnd: 499
    crossApplicationTracer: true
    distributedTracer: true

metrics:
  float64: [gauge, histogram, distribution, timeInMilliseconds]